#!/bin/bash
##
## Author: Belaja-akacija
## Version: 0.1
##
## Description:
## Launch a scratchpad for me in vim, based on the current date.
## If the current date file already exists, then just open that file.
## Automatically, the reminders from the previous day will be at the top of the file.
## Trying to write the script as modularly as possible, so new features can be patched in easily.
##
## TODO:
## Directory structure by month
## Add persistence of reminders, denoted by [!] at the end of an entry
## Maybe be able to chain together flags, something like e.g. [!*] -- pin this reminder to the very top; and other subtle quality of life fixes.
## Check the state of the header in the current scratchpad and compare it to the previous day's reminders. Overwrite if doesn't match.

DATE=$(date +"%d-%m-%Y")
YESTERDAY=$(date +"%d-%m-%Y" --date="yesterday")
TEMP="/tmp/$YESTERDAY.tmp"
touch "$TEMP"
CURR_MONTH=$(date +"%B")
DIR=$HOME/.local/share/scratchpad/$CURR_MONTH
REMINDER=$(grep -E "\[\+\]$" "$DIR/$YESTERDAY" 2>/dev/null)
echo "$REMINDER" > $TEMP
REPLACER=$(sed -i "s/\[+\]/\[\?\]/g" "$TEMP")

GiveReminder(){
  if test -f "$DIR/$DATE"; then

    if [[ $(sed -n 1p "$DIR/$DATE") != "+--------------------+" ]]; then # First prepend in the previous day's reminders

       echo "+--------------------+
Yesterday's reminders:

$(cat $TEMP)
+--------------------+

$(cat $DIR/$DATE)" > $DIR/$DATE
      else
        OpenScratchpad

        exit 0
    fi
    OpenScratchpad
  fi

  exit 0
}

OpenScratchpad(){
  if ! [[ "$(command -v nvim)" ]]; then
    vim -c "Goyo" "$DIR/$DATE"
  else
    nvim -c "Goyo" "$DIR/$DATE" # Open the current day's scratchpad in neovim
  fi

  exit 0
}


Init(){
  if ! test -f "$DIR/$DATE"; then
    touch $DIR/$DATE
  fi
  GiveReminder
}

if ! test -d "$DIR"; then
  mkdir -p -v "$DIR"
fi
Init

exit 0
